# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f017f0274d397966dd0b815ae26eddfca1fb341ef980b5d6213c74e61f15a13898a426adc58a19da65ef8cb489741e2a05ebcb02a2ea81f11e42f66194c3c7c1

test:
  secret_key_base: 7bf18ece78905252cfed866a76f01cc9b316c7e5ab08663f47a6ef2438d828ff8e4532863d97e94cdd5943c16e6078246b9642ac2504d98d1fbd91e737ac5657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
